# Generated by Django 4.2.6 on 2023-10-18 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("qrcode", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="name",
            field=models.CharField(default="Default Name", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="qrcode",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
