# Generated by Django 4.2.6 on 2023-10-19 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("qrcode", "0002_qrcode_name_alter_qrcode_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="qrcode",
            old_name="disabled",
            new_name="active",
        ),
    ]
