# Generated by Django 4.2.6 on 2023-10-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qrcode", "0003_rename_disabled_qrcode_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcode",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
